In [15]:
import numpy as np

x = np.array([1, 2, 3, 4])
y = np.array([2, 4, 6, 8])

cov_matrix = np.cov(x, y, bias=True)
print(cov_matrix)

[[1.25 2.5 ]
 [2.5  5.  ]]


In [17]:
# calculate a variance along specific axis
v = np.array([[1], [0]])
print(v.T @ cov_matrix @ v)
v = np.array([[0], [1]])
print(v.T @ cov_matrix @ v)

[[1.25]]
[[5.]]


In [20]:
tmp_x = np.array([[1,2,3], [0,0,0]])
v = np.array([[1], [1]])
print(v.T @ tmp_x)

[[1 2 3]]


In [24]:
print(tmp_x.T @ v)

[[1]
 [2]
 [3]]


In [ ]:
# conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia

In [8]:
print(((x - x.mean())**2).sum()/4)
print(((y - y.mean())**2).sum()/4)

1.25
5.0


In [9]:
print(( (x - x.mean()) * (y - y.mean()) ).sum() / 4 )

2.5


In [14]:
np.cov(np.array([x, y]))

array([[1.66666667, 3.33333333],
       [3.33333333, 6.66666667]])

In [ ]:
print("hello world")

hello world
