# Surprise
$$U(x)=\log\frac{1}{P(x)}$$

In [8]:
import numpy as np

np.set_printoptions(precision=4)

acc = np.array([
    [6,  1],
    [1, 10],
    [7,  7]
])
print(f'counts each cases:\n{acc}')
prob = acc / acc.sum(axis=1).reshape(-1, 1)
print(f'probability:\n{prob}')
surp = np.log2(1 / prob)
print(f'surprise:\n{surp}')

counts each cases:
[[ 6  1]
 [ 1 10]
 [ 7  7]]
probability:
[[0.8571 0.1429]
 [0.0909 0.9091]
 [0.5    0.5   ]]
surprise:
[[0.2224 2.8074]
 [3.4594 0.1375]
 [1.     1.    ]]


# Entropy
- Expected surprise
$$S(x) = \sum_xU(x)P(x)$$
$$= \sum_x\log(\frac{1}{p(x)})p(x)$$

In [10]:
entropy = (prob * surp).sum(axis=1)
print('entropy:\n', entropy)

entropy:
 [0.5917 0.4395 1.    ]
